GET http://localhost:3000/users

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "teste4",
    "email": "teste4@gmail.com",
    "gender": "Masculino",
    "ageRange": "13 - 17 anos",
    "password": "12345"
}


###

POST http://localhost:3000
Content-Type: application/json

{
    "email": "teste4@gmail.com",
    "password": "1234"
}